"use client";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { AmbientVideo } from "@/components/ambient-video";
function enter(){window.location.replace(window.matchMedia("(max-width: 767px)").matches?"/c":"/telao/pleitos");}
export function CampaignEntry(){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch("/api/telao/registro",{cache:"no-store",signal:controller.signal}).then(r=>{if(r.ok)enter();}).catch(()=>{});return()=>controller.abort();},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/telao/registro",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome:name,whatsapp:phone}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok){setError(data.erro||"Confira seus dados e tente novamente.");return;}enter();}catch{setError("Sem conexão agora. Seus dados continuam preenchidos; tente novamente.");}finally{setBusy(false);}};
 return <main className="usage-entry"><section className="usage-form-area"><a className="usage-brand" href="/">Vitória Sempre<span>Inteligência de campanha</span></a><div className="usage-form"><h1>A sua campanha,<br/>em uma só visão.</h1><p>Um registro simples para entrar na central.<br/>Sem usuário e senha.</p><form onSubmit={submit}>
 <label htmlFor="usage-name">Seu nome<input id="usage-name" name="name" autoComplete="name" required minLength={2} maxLength={80} placeholder="Como podemos chamar você?" value={name} onChange={e=>setName(e.target.value)}/></label><label htmlFor="usage-phone">WhatsApp com DDD<input id="usage-phone" name="tel" autoComplete="tel" type="tel" inputMode="tel" required minLength={10} maxLength={20} placeholder="(11) 99999-9999" value={phone} onChange={e=>setPhone(e.target.value)}/></label><small>Preencha uma vez. Neste navegador, os próximos acessos vão direto para a central.</small>
 {error&&<p className="usage-error" role="alert">{error}</p>}<button className="usage-submit" disabled={busy}>{busy?"Um momento…":"Entrar na central"}<ArrowRight size={18}/></button></form><div className="usage-note"><ShieldCheck size={17}/><span>Registro de uso · Ambiente interno dos partidos</span></div></div><footer>Uso interno. Plataforma independente, sem chancela do TSE.</footer></section><section className="usage-visual" aria-label="Ambientação da central de campanha"><AmbientVideo/><div className="usage-video-caption"><strong>O cenário inteiro.<br/>As decisões essenciais.</strong><span>Vídeo ilustrativo gerado por IA · Veo 3.1 Fast / Gemini</span></div></section></main>;
}
