"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Clock3, Activity, Newspaper, ShieldCheck, X, MapPin, ArrowUpRight } from "lucide-react";
import type { Apuracao, PleitoSnapshot } from "@/lib/telao/tse-apuracao";
import type { Panorama } from "@/lib/telao/tse-nacional";
import type { BocaPesquisa } from "@/lib/telao/boca-de-urna";
import type { Noticia } from "@/lib/telao/noticias";
import { weightedProgress } from "@/lib/telao/research-audit";
import { UF_NOME, REGIAO } from "@/lib/telao/ufs";
import { SocialRadar } from "./social-radar";
import { Methodology } from "./methodology";
import { BrazilMap } from "./brazil-map";
const fmt = (n: number) => n.toLocaleString("pt-BR", { maximumFractionDigits: 1 });
const text = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
type Audience = { total: number; online: number; definition: string; groups: {uf:string;total:number;online:number;cities:{city:string;total:number;online:number}[]}[] };
export function CampaignMonitor({ p, ap, pesquisa, panorama, noticias, uf, now, onSelectUf, partyColor }: { p:PleitoSnapshot; ap?:Apuracao; pesquisa?:BocaPesquisa; panorama?:Panorama|null; noticias:Noticia[];uf:string;now:number;onSelectUf:(uf:string)=>void;partyColor:(party:string)=>string }) {
 const [open,setOpen]=useState(false), [query,setQuery]=useState(""), [newsScope,setNewsScope]=useState("todas"), [region,setRegion]=useState("Estado"), [audience,setAudience]=useState<Audience|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ const node=dialog.current; if(open) node?.showModal(); else node?.close(); },[open]);
 useEffect(()=>{ let alive=true; const update=()=> { if(document.visibilityState!=="visible") return; fetch("/api/telao/presence",{method:"POST"}).then(()=>fetch("/api/telao/presence",{cache:"no-store"})).then(r=>r.ok?r.json():null).then(d=>{if(alive)setAudience(d);}).catch(()=>{}); }; update();const interval=setInterval(update,60000);return()=>{alive=false;clearInterval(interval);}; },[]);
 const parties=useMemo(()=>{const m=new Map<string,number>(); for(const c of p.candidatos)m.set(c.p,(m.get(c.p)??0)+1); return [...m].sort((a,b)=>b[1]-a[1]);},[p]);
 const filtered=useMemo(()=> { const seen=new Set<string>(); const term=text(query.trim()); const cargo=p.id.startsWith("dep-")?"deputad":p.id.startsWith("governador")?"governad":p.id.startsWith("senador")?"senad":"presiden";
 return noticias.filter(n=>{const t=text(n.titulo+" "+n.resumo);const identity=text(n.titulo);if(seen.has(identity))return false;seen.add(identity);return(!term||t.includes(term))&&(newsScope==="todas"||newsScope==="estado"?newsScope==="todas"||t.includes(text(UF_NOME[uf])):t.includes(cargo));}).slice(0,12); },[noticias,query,newsScope,p.id,uf]);
 const rows=(panorama?.territorios??[]).filter(r=>r.pleito===p.id&&(region==="Estado"?r.uf===uf:region==="Brasil"||REGIAO[r.uf]===region));
 const progress=region==="Estado"&&ap ? (ap.secoesTotal ?100*ap.secoesTot/ap.secoesTotal:null):weightedProgress(rows);
 const available=ap?.status==="apurando"||ap?.status==="finalizado";
 const time=now?new Date(now).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"}):"—";
 return <div className="cm-root"><div className="cm-rail">
 <button className="cm-clock" onClick={()=>setOpen(true)}><Clock3 size={17}/><span>Brasília<strong>{time}</strong></span></button>
 <button onClick={()=>setOpen(true)}><Activity size={17}/><span>Urnas · {ap?.uf?.toUpperCase()??uf.toUpperCase()}<strong>{available?fmt(ap!.pctUrnas)+"%":"Aguardando TSE"}</strong></span></button>
 <button onClick={()=>setOpen(true)}><ShieldCheck size={17}/><span>Pesquisa<strong>{pesquisa?"Validação pendente":"Sem levantamento"}</strong></span></button>
 <button onClick={()=>window.location.assign("/telao/noticias")}><Newspaper size={17}/><span>Notícias · todos os cargos<strong>{noticias.length} no radar</strong></span></button>
 <button className="cm-open" onClick={()=>setOpen(true)}>Dia de campanha <ArrowUpRight size={17}/></button></div>
 <dialog ref={dialog} className="cm-dialog" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="cm-title"><div className="cm-top"><div><h2 id="cm-title">Cada sinal, no seu contexto.</h2><p>{p.titulo} · dados oficiais, notícias e qualidade das fontes</p></div><button autoFocus onClick={()=>setOpen(false)} aria-label="Fechar central"><X size={23}/></button></div>
 <div className="cm-grid"><SocialRadar p={p} uf={uf}/><section><h3><Clock3 size={18}/> Ritmo da apuração</h3><div className="cm-kpis"><div><span>Votos válidos</span><strong>{available?fmt(ap!.votosValidos):"—"}</strong></div><div><span>Última totalização TSE</span><strong>{ap?.hora||"Aguardando"}</strong></div><div><span>Chance de segundo turno</span><strong>{p.id==="presidente"||p.id.startsWith("governador")?"Indisponível":"Não se aplica"}</strong></div></div><p>Sem modelo validado, não atribuímos probabilidade de segundo turno. Agenda e metas pessoais dependem de cadastro e integração; nenhum compromisso é inventado.</p><Methodology pesquisa={pesquisa} candidates={p.candidatos}/></section>
 <section><h3><MapPin size={18}/> Territórios</h3><label className="cm-label">Abrangência <select value={region} onChange={e=>setRegion(e.target.value)}>{["Estado","Brasil","Sul","Sudeste","Norte","Nordeste","Centro-Oeste"].map(x=><option key={x}>{x}</option>)}</select></label><div className="cm-kpis"><div><span>Seções totalizadas</span><strong>{progress===null?"Indisponível":fmt(progress)+"%"}</strong></div><div><span>UFs com denominador conhecido</span><strong>{rows.filter(r=>r.secoesTotal>0).length}/{rows.length||1}</strong></div></div><p>{p.id==="presidente"?"Mesma eleição presidencial em cada recorte.":"Comparação do andamento de eleições independentes por UF; não constitui uma eleição nacional deste cargo."} Município e zona podem ser selecionados no filtro do telão. Seção individual: indisponível nesta integração. UF sem dados não conta como apurada.</p></section>
 <section><h3>Composição das candidaturas</h3><svg viewBox="0 0 320 170" role="img" aria-label={`Hemiciclo de ${p.candidatos.length} candidaturas cadastradas, por partido. Não representa cadeiras.`}><title>Candidaturas por partido; cada ponto representa uma fração do cadastro</title>{Array.from({length:Math.min(120,p.candidatos.length)},(_,i)=>{const count=Math.min(120,p.candidatos.length),fraction=(i+.5)/count;let cursor=0;const party=parties.find(([,n])=>{cursor+=n/p.candidatos.length;return fraction<=cursor;})?.[0]??"";const rows=count<12?1:4,row=i%rows,rowCount=Math.ceil((count-row)/rows),angle=Math.PI*(.04+.92*(Math.floor(i/rows)+.5)/Math.max(1,rowCount)),radius=100+row*15;return <circle key={i} cx={160+Math.cos(angle)*radius} cy={160-Math.sin(angle)*radius} r={4} fill={partyColor(party)}><title>{party} · composição do cadastro</title></circle>;})}</svg><div className="cm-party-list">{parties.map(([party,n])=><div key={party}><i style={{background:partyColor(party)}}/><strong>{party}</strong><span>{n} candidatos</span><b>{fmt(100*n/Math.max(1,p.candidatos.length))}%</b></div>)}</div><p>Percentual de candidatos cadastrados, não de votos ou cadeiras. Lista exibida: {p.candidatos.length} de {p.total} no cadastro.</p></section>
 <section><h3>Votos por partido e agremiação</h3>{available && !!ap?.partidosIndividuais?.length && <div className="cm-party-list">{ap.partidosIndividuais.map(party=><div key={party.sigla}><i style={{background:partyColor(party.sigla)}}/><strong>{party.sigla}</strong><span>{fmt(party.total)} votos válidos</span><b>{fmt(party.pct)}%</b><small>{fmt(party.nominais)} nominais + {fmt(party.legenda)} legenda</small></div>)}</div>}{available&&ap?.partidos?.length?<div className="cm-party-list">{ap.partidos.map(party=><div key={party.sigla}><strong>{party.sigla}</strong><span>{party.partidos.join(" + ")}</span><b>{fmt(party.pct)}%</b><small>{fmt(party.nominais)} nominais + {fmt(party.legenda)} legenda</small></div>)}</div>:<p>Percentuais disponíveis quando o TSE publicar votos válidos e os totais por agremiação. Federações são mantidas como agremiações, sem rateio artificial entre partidos.</p>}</section>
 <section className="cm-news"><h3><Newspaper size={18}/> Radar de notícias</h3><a href="/telao/noticias">Ver lista completa de todos os cargos ↗</a><div className="cm-news-controls"><input aria-label="Filtrar notícias por nome ou partido" placeholder="Nome do candidato ou partido" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Recorte de notícias" value={newsScope} onChange={e=>setNewsScope(e.target.value)}><option value="cargo">Cargo atual</option><option value="estado">Estado atual</option><option value="todas">Todas</option></select></div>{filtered.length?filtered.map(n=><a key={n.link} href={n.link} target="_blank" rel="noreferrer"><small>{n.nome} · {new Date(n.t).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</small><strong>{n.titulo}</strong></a>):<p>Nenhuma notícia corresponde ao filtro. Busca textual em títulos e resumos; homônimos exigem conferência editorial.</p>}</section>
 {audience&&<section><h3>Presença da equipe</h3><div className="cm-kpis"><div><span>Registros desde a ativação</span><strong>{audience.total}</strong></div><div><span>Online agora</span><strong>{audience.online}</strong></div></div><div className="cm-map"><BrazilMap uf={uf} onSelect={onSelectUf} audience={audience.groups}/></div><div className="cm-party-list">{audience.groups.flatMap(g=>g.cities.map(c=><div key={g.uf+c.city}><strong>{c.city} · {g.uf.toUpperCase()}</strong><span>{c.total} registros</span><b>{c.online} online</b></div>))}</div><p>{audience.definition} Sem nomes, telefones ou IPs neste monitor.</p></section>}
 </div><footer className="cm-disclaimer">Acesso restrito · Uso interno dos partidos · Ambiente de acompanhamento independente, sem chancela do TSE.</footer></dialog></div>;
}
